defaults:
  - override hydra/launcher: slurm
  - _self_

hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  job:
    chdir: True
  run:
    dir: /iris/u/kylehsu/outputs/modular/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}
  sweeper:    # only invoked if --multirun is used
#    params:
#      wandb.group: image_slice
#      data.slice: 0.1, 0.6, 1.0, 1.3, 1.5
##      experiment.seed: 43
#      experiment.seed: 44, 45, 46
    params:
      wandb.group: image_correlated
      data.covariance: 0.9
      data.correlated_sampling_factor: 0, 0.01, 0.013, 0.0175, 0.02
#      experiment.seed: 43
      experiment.seed: 44, 45, 46

optim:
  num_steps: 100000
  learning_rate: 0.0002
  weight_decay: 0.1
  clip: 1.

model:
  _partial_: True
  _target_: disentangle.models.Autoencoder
  encoder:
    _partial_: True
    _target_: disentangle.nn.ResidualEncoder
  decoder:
    _partial_: True
    _target_: disentangle.nn.ResidualDecoder
    normalize_outputs: False
  latent_size: ???
  reconstruction_loss_fn: binary_cross_entropy
  lambdas:
    reconstruct: 1
  regularized_attributes:
    - encoder
    - decoder
  quantize_latents: True
  num_quantized_values: 6

experiment:
  seed: 1000

data:
  name: isaac3d
  possible_dirs:
    - /scr-ssd/kylehsu/data
    - /scr/kylehsu/data
  seed: 0
  batch_size: 16
  slice: 0
  correlated_sampling_factor: 0
  covariance: 0

eval:
  period: 2e4
  num_vis_rows:
    val: 3
  num_vis_cols: 16
  num_intervene_cols: 8
  num_intervene_values: 10

wandb:
  entity: iris_viscam
  project: modular
  name: null
  group: qlae
  job_type: null

debug: False

checkpoint:
  period: 100000