defaults:
  - override hydra/launcher: slurm
  - _self_

hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  job:
    chdir: True
  run:
    dir: /iris/u/kylehsu/outputs/modular/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}
  sweeper:    # only invoked if --multirun is used
#    params:
#      wandb.group: linear_slice
#      data.slice: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5
#      experiment.seed: 43, 44, 45, 46, 47, 48, 49, 50, 51, 52
#    params:
#      wandb.group: linear_correlated
#      data.covariance: 0.9
#      data.correlated_sampling_factor: 0, 0.002857, 0.005714, 0.008571, 0.011429, 0.014286, 0.017143, 0.02, 0.022857, 0.025714, 0.028571, 0.031429, 0.034286, 0.037143, 0.04
#      experiment.seed: 43, 44, 45, 46, 47, 48, 49, 50, 51, 52

optim:
  n_steps: 200000
  learning_rate: 0.001
  weight_decay: 0
  small_init: True
  small_init_scale: 0.1

model:
  _partial_: True
  _target_: scripts.train_toy.MLPAutoencoder
  d_input: ${data.d_source}
  d_latent: 6
  d_hidden: 16
  n_layers: 2
  mlp_activation: relu
  latent_activation: identity
  lambdas:
    reconstruction: 10
    activation_energy: 1e-1
    activation_negativity: 10
    weight_energy: 1e-3
  negativity_loss: relu   # squared or relu
  regularize_biases: False
  normalize_weight_energy: False

#model:
#  _partial_: True
#  _target_: scripts.train_toy.MLPAutoencoder
#  d_input: ${data.d_data}
#  d_latent: 4
#  d_hidden: 256
#  n_layers: 3
#  mlp_activation: relu
#  latent_activation: identity
#  lambdas:
#    reconstruction: 10
#    activation_energy: 1
#    activation_negativity: 10
#    weight_energy: 3e-6
#  negativity_loss: relu   # squared or relu
#  regularize_biases: False
#  normalize_weight_energy: False

experiment:
  seed: 43

data:
  name: square
  d_source: 3
  n_values_per_source: 21
  possible_dirs:
    - /scr-ssd/kylehsu/data
    - /scr/kylehsu/data
  seed: 8254  # 8254
  batch_size: 512
  slice: 0
  correlated_sampling_factor: 0.
  covariance: 0.

#data:
#  name: square_mlp
#  d_source: 2
#  d_data: 64
#  mlp_activation: relu
#  n_mlp_layers: 1   # 1
#  d_mlp_hidden: 16  # 16
#  n_train: 200000
#  n_val: 10000
#  possible_dirs:
#    - /scr-ssd/kylehsu/data
#    - /scr/kylehsu/data
#  seed: 8254  # 8254
#  buffer_size: 10000
#  batch_size: 512
#  slice: 0

eval:
  period: 5e4

wandb:
  entity: iris_viscam
  project: modular
  name: null
  group: null
  job_type: null

debug: False

checkpoint:
  period: ${eval.period}