defaults:
  - override hydra/launcher: slurm
  - _self_

hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  job:
    chdir: True
    env_set:
      HOME: /iris/u/kylehsu
  run:
    dir: /iris/u/kylehsu/runs/modular/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}
  sweeper:    # only invoked if --multirun is used
    params:
      experiment.seed: 410, 411, 412, 413, 414, 415, 416, 417, 418, 419
      data.name: independent, corner:6, corner:8, corner:10, corner:12, diagonal_remove:0, diagonal_remove:1, diagonal_remove:2, diagonal_remove:3, diagonal_strengthen:500, diagonal_strengthen:1000, diagonal_strengthen:1500, diagonal_strengthen:2500

optim:
  num_steps: 100000
  learning_rate: 0.0002
  weight_decay: 0.1
  clip: 1.
  batch_size: 64

model:
  _partial_: True
  _target_: disentangle.models.Autoencoder
  encoder:
    _partial_: True
    _target_: disentangle.nn.ResidualEncoder
  decoder:
    _partial_: True
    _target_: disentangle.nn.ResidualDecoder
    normalize_outputs: False
  latent_size: ???
  reconstruction_loss_fn: binary_cross_entropy
  lambdas:
    reconstruct: 1
  regularized_attributes:
    - encoder
    - decoder
  quantize_latents: True
  num_quantized_values: 10

experiment:
  seed: 401

data:
#  name: independent
  name: corner:10
#  name: diagonal_remove:3
#  name: diagonal_strengthen:2400
  seed: 0

eval:
  period: 25000
  num_vis_rows:
    val: 3
  num_vis_cols: 16
  num_intervene_cols: 8
  num_intervene_values: 10

wandb:
  entity: iris_viscam
  project: modular
  name: null
  group: arxiv_qlae
  job_type: null

debug: False

checkpoint:
  period: ${eval.period}