defaults:
  - override hydra/launcher: slurm
  - _self_

hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  job:
    chdir: True
    env_set:
      HOME: /iris/u/kylehsu
  run:
    dir: /iris/u/kylehsu/runs/modular/${now:%Y-%m-%d}/${now:%H-%M-%S}
#    dir: /Users/kylehsu/runs/modular/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}
  sweeper:    # only invoked if --multirun is used
    params:
      data.name: independent, corner:0.3, corner:0.4, corner:0.5, corner:0.6, corner:0.7, corner:0.8, corner:0.9, corner:1.0, diagonal_strengthen:10, diagonal_strengthen:20, diagonal_strengthen:30, diagonal_strengthen:50, diagonal_strengthen:100, diagonal_strengthen:150, diagonal_strengthen:200, diagonal_strengthen:300, diagonal_remove:0.1, diagonal_remove:0.2, diagonal_remove:0.3, diagonal_remove:0.4, diagonal_remove:0.5, diagonal_remove:0.6, diagonal_remove:0.7, diagonal_remove:0.9
      experiment.seed: 402, 403, 404, 405, 406, 407, 408, 409, 410
#      experiment.seed: 401
#    params:
#      wandb.group: linear_slice
#      data.slice: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5
#      experiment.seed: 43, 44, 45, 46, 47, 48, 49, 50, 51, 52
#    params:
#      wandb.group: linear_correlated
#      data.covariance: 0.9
#      data.correlated_sampling_factor: 0, 0.002857, 0.005714, 0.008571, 0.011429, 0.014286, 0.017143, 0.02, 0.022857, 0.025714, 0.028571, 0.031429, 0.034286, 0.037143, 0.04
#      experiment.seed: 43, 44, 45, 46, 47, 48, 49, 50, 51, 52


optim:
  n_steps: 200000
  learning_rate: 0.001
  weight_decay: 0
  small_init_scale: 0.3
  batch_size: 512

model:
  _partial_: True
  _target_: scripts.train_autoencoder_low_d.MLPAutoencoder
  d_input: 3
  d_latent: 6
  d_hidden: 16
  n_mlp_layers: 2
  lambdas:
    reconstruction: 1
    activation_energy: 1e-2
    activation_negativity: 1
    weight_energy: 1e-4
experiment:
  seed: 999
# works
#  lambdas:
#    reconstruction: 1
#    activation_energy: 1e-2
#    activation_negativity: 1
#    weight_energy: 1e-5
#experiment:
#  seed: 43

#  lambdas:
#    reconstruction: 1
#    activation_energy: 1e-2
#    activation_negativity: 1
#    weight_energy: 1e-4
#experiment:
#  seed: 888
data:
  name: independent
#  path: /Users/kylehsu/code/modular/low_d_sources.npz
  path: /iris/u/kylehsu/code/modular/low_d_sources.npz
  seed: 8254
  d_source: 3
  n_values_per_source: 21

eval:
  period: 5e4

wandb:
  entity: iris_viscam
  project: modular
  name: null
  group: arxiv_low_d
  job_type: null

debug: False

checkpoint:
  period: ${eval.period}