# @package hydra.launcher
#partition: iris-hi
#account: iris
#exclude: iris-hp-z8,iris-hgx-1
partition: viscam
account: viscam
exclude:
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 600
cpus_per_task: 16
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 12
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
qos: null
comment: null
constraint: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters:
  export: PATH,USER,SUBMITIT_EXECUTOR,SLURM_MPI_TYPE=pmi2,HYDRA_FULL_ERROR=1,LD_LIBRARY_PATH
array_parallelism: 256
setup: null


